import { ROUTES } from "../../shared/constants";
import { formatNumber } from "../../utils/helper";

export const quickActions = [
  {
    title: 'Add Class',
    icon: 'fa-chalkboard',
    bgColor: 'bg-indigo-100',
    hoverColor: 'hover:border-indigo-300 hover:bg-indigo-50',
    iconColor: 'text-indigo-600',
    groupHover: 'group-hover:bg-indigo-200',
    route: ROUTES.ADMIN_CLASSES,
    openForm: true,
  },
  {
    title: 'Add Teacher',
    icon: 'fa-user-plus',
    bgColor: 'bg-purple-100',
    hoverColor: 'hover:border-purple-300 hover:bg-purple-50',
    iconColor: 'text-purple-600',
    groupHover: 'group-hover:bg-purple-200',
    route: ROUTES.ADMIN_TEACHERS,
    openForm: true,
  },
  {
    title: 'Create Notice',
    icon: 'fa-bullhorn',
    bgColor: 'bg-cyan-100',
    hoverColor: 'hover:border-cyan-300 hover:bg-cyan-50',
    iconColor: 'text-cyan-600',
    groupHover: 'group-hover:bg-cyan-200',
    route: ROUTES.ADMIN_NOTICES_CREATE,
  },
  {
    title: 'Schedule Exam',
    icon: 'fa-calendar-plus',
    bgColor: 'bg-green-100',
    hoverColor: 'hover:border-green-300 hover:bg-green-50',
    iconColor: 'text-green-600',
    groupHover: 'group-hover:bg-green-200',
    route: ROUTES.ADMIN_EXAMS,
  },
  {
    title: 'Generate Report',
    icon: 'fa-file-invoice',
    bgColor: 'bg-orange-100',
    hoverColor: 'hover:border-orange-300 hover:bg-orange-50',
    iconColor: 'text-orange-600',
    groupHover: 'group-hover:bg-orange-200',
    route: ROUTES.ADMIN_REPORTS,
  },
  {
    title: 'Settings',
    icon: 'fa-cog',
    bgColor: 'bg-red-100',
    hoverColor: 'hover:border-red-300 hover:bg-red-50',
    iconColor: 'text-red-600',
    groupHover: 'group-hover:bg-red-200',
    route: ROUTES.ADMIN_SETTINGS,
  },
];

export const months = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'];

export const stats = (quickStats: any) => quickStats ? [
  {
    title: 'Total Students',
    value: formatNumber(quickStats.totalStudents),
    change: 'Active',
    changeText: `${quickStats.totalEnrolled} enrolled`,
    icon: 'fa-user-graduate',
    bgColor: 'bg-indigo-100',
    iconColor: 'text-indigo-600',
    changeColor: 'text-blue-600',
    changeBg: 'bg-blue-50',
  },
  {
    title: 'Total Teachers',
    value: formatNumber(quickStats.totalTeachers),
    change: 'Active',
    changeText: 'Teaching staff',
    icon: 'fa-chalkboard-teacher',
    bgColor: 'bg-purple-100',
    iconColor: 'text-purple-600',
    changeColor: 'text-blue-600',
    changeBg: 'bg-blue-50',
  },
  {
    title: 'Total Classes',
    value: formatNumber(quickStats.totalClasses),
    change: 'Active',
    changeText: 'Active classes',
    icon: 'fa-chalkboard',
    bgColor: 'bg-cyan-100',
    iconColor: 'text-cyan-600',
    changeColor: 'text-blue-600',
    changeBg: 'bg-blue-50',
  },
  {
    title: 'Total Lectures',
    value: formatNumber(quickStats.totalLectures),
    change: 'Scheduled',
    changeText: 'Upcoming lectures',
    icon: 'fa-book',
    bgColor: 'bg-green-100',
    iconColor: 'text-green-600',
    changeColor: 'text-blue-600',
    changeBg: 'bg-blue-50',
  },
] : [];