export const USER_ROLES = {
  ADMIN: 'ADMIN',
  TEACHER: 'TEACHER',
  STUDENT: 'STUDENT',
  PARENT: 'PARENT',
} as const;

export type UserRole = typeof USER_ROLES[keyof typeof USER_ROLES];

export const ROUTES = {
  LOGIN: '/login',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_CLASSES: '/admin/classes',
  ADMIN_TEACHERS: '/admin/teachers',
  ADMIN_STUDENTS: '/admin/students',
  ADMIN_LECTURES: '/admin/lectures',
  ADMIN_SUBJECTS: '/admin/subjects',
  ADMIN_NOTICES: '/admin/notices',
  ADMIN_NOTICES_CREATE: '/admin/notices/create',
  ADMIN_EXAMS: '/admin/exams',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_PROFILE: '/admin/profile',
  TEACHER_DASHBOARD: '/teacher/dashboard',
  TEACHER_CLASSES: '/teacher/classes',
  TEACHER_CLASS_DETAIL: '/teacher/classes/:id',
  TEACHER_CLASS_ATTENDANCE: '/teacher/classes/:id/attendance',
  TEACHER_ATTENDANCE: '/teacher/attendance',
  TEACHER_QUERIES: '/teacher/queries',
  TEACHER_SUBJECTS: '/teacher/subjects',
  TEACHER_SUBJECT_DETAIL: '/teacher/subjects/:id',
  TEACHER_PROFILE: '/teacher/profile',
  STUDENT_DASHBOARD: '/student/dashboard',
  STUDENT_EXAMS: '/student/exams',
  STUDENT_NOTIFICATIONS: '/student/notifications',
  STUDENT_RECORDS: '/student/records',
  STUDENT_SUBJECTS: '/student/subjects',
  STUDENT_SUBJECT_DETAIL: '/student/subjects/:id',
  STUDENT_PROFILE: '/student/profile',
  PARENT_DASHBOARD: '/parent/dashboard',
  PARENT_ATTENDANCE: '/parent/attendance',
  PARENT_RECORDS: '/parent/records',
  PARENT_SUBJECTS: '/parent/subjects',
  PARENT_SUBJECT_DETAIL: '/parent/subjects/:id',
  PARENT_PROFILE: '/parent/profile',
  STUDENT_HELP_SUPPORT: '/student/help-support',
  PARENT_HELP_SUPPORT: '/parent/help-support',
} as const;

