/**
 * Students Domain Types
 */

// Domain Types (used in the application)
export interface StudentAddress {
  street?: string;
  city?: string;
  state?: string;
  zipCode?: string;
}

export interface Student {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  studentId: string;
  age?: number;
  gender?: 'male' | 'female' | 'other';
  phone?: string;
  grade?: string;
  address?: StudentAddress;
  enrolledAt?: Date;
  isActive: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface CreateStudentData {
  firstName: string;
  lastName: string;
  email: string;
  studentId: string;
  age?: number;
  gender?: 'male' | 'female' | 'other';
  phone?: string;
  grade?: string;
  address?: StudentAddress;
  enrolledAt?: string; // Optional, auto-generated by API
  isActive?: boolean; // Optional, defaults to true
}

export interface UpdateStudentData extends Partial<CreateStudentData> {
  id: string;
}

// API Response Types (camelCase with _id)
export interface StudentAddressApiDTO {
  street?: string;
  city?: string;
  state?: string;
  zipCode?: string;
}

export interface StudentApiDTO {
  _id: string;
  firstName: string;
  lastName: string;
  email: string;
  studentId: string;
  age?: number;
  gender?: 'male' | 'female' | 'other';
  phone?: string;
  grade?: string;
  address?: StudentAddressApiDTO;
  enrolledAt?: string; // ISO date string
  isActive?: boolean;
  createdAt?: string; // ISO date string
  updatedAt?: string; // ISO date string
}

// Projected fields from list endpoint (only these fields are returned)
export interface StudentListApiDTO {
  _id: string;
  firstName: string;
  lastName: string;
  email: string;
  studentId: string;
  grade?: string;
}

// API Response Wrappers
export interface StudentsApiResponse {
  success: boolean;
  count: number;
  data: StudentListApiDTO[]; // List endpoint returns projected fields only
}

export interface StudentApiResponse {
  success: boolean;
  data: StudentApiDTO; // Detail endpoint returns full student object
  message?: string;
}

export interface CreateStudentApiResponse {
  success: boolean;
  message: string;
  data: StudentApiDTO;
}

export interface UpdateStudentApiResponse {
  success: boolean;
  message: string;
  data: StudentApiDTO;
}

export interface DeleteStudentApiResponse {
  success: boolean;
  message: string;
}
